// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-02-14, 9:34:32 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/composables/**/*.{js,ts,mjs}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/utils/**/*.{js,ts,mjs}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/steph/Documents/GitHub/community-mining-pool/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;